# Generated by Django 3.2.8 on 2021-11-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0017_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='relation',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
